version: '3.8'
services:
  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    ports: ["9116:9116"]
    volumes:
      - ./configs/snmp-simple.yml:/etc/snmp_exporter/snmp.yml:ro
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports: ["9090:9090"]
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prom:/prom:Z
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prom
      - --web.enable-lifecycle
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports: ["3001:3000"]        # dùng 3001 để tránh trùng
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  prom_data:
  grafana_data:
