version: '3.8'
services:
  snmp-exporter:
    image: prom/snmp-exporter:v0.24.1
    container_name: snmp-exporter
    network_mode: host
    volumes:
      - ./configs/snmp.yml:/etc/snmp_exporter/snmp.yml:ro
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prom:/prom:Z
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prom
      - --storage.tsdb.retention.time=15d
      - --web.enable-lifecycle
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    environment:
      - GF_SERVER_HTTP_PORT=3001
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    network_mode: host
    volumes:
      - loki_data:/loki
      - ./configs/loki.yml:/etc/loki/loki.yml
    command:
      - --config.file=/etc/loki/loki.yml
    restart: unless-stopped

volumes:
  loki_data:
  prom_data:
  grafana_data:
