server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://192.168.10.18:3100/loki/api/v1/push

scrape_configs:
  # Collect Docker container logs for Speedtest Exporters (Static config)
  - job_name: docker-speedtest
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-speedtest
          service: speedtest-exporter
          host: speedtest-host
          __path__: /var/lib/docker/containers/*/*-json.log


 

  # Collect system logs from /var/log
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          host: ${HOSTNAME}
          __path__: /var/log/*log

  # Collect messages
  - job_name: messages
    static_configs:
      - targets:
          - localhost
        labels:
          job: messages
          host: ${HOSTNAME}
          __path__: /var/log/messages



  # Syslog receiver (TCP port 514) 
  - job_name: syslog-tcp
    syslog:
      listen_address: 0.0.0.0:1515
      listen_protocol: tcp
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: syslog-tcp
        host: ${HOSTNAME}
