groups:
  - name: network_alerts
    rules:
      # SNMP Exporter Alerts
      - alert: HighCPUUsage
        expr: avg by (instance, device, gw) (hrProcessorLoad) > 85
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "Device {{ $labels.device }} ({{ $labels.gw }}) CPU usage is {{ $value }}%"
          
      - alert: HighMemoryUsage
        expr: 100 * (
          sum by (instance, device, gw) (hrStorageUsed{hrStorageType="1.3.6.1.2.1.25.2.1.2"} * hrStorageAllocationUnits{hrStorageType="1.3.6.1.2.1.25.2.1.2"})
          /
          sum by (instance, device, gw) (hrStorageSize{hrStorageType="1.3.6.1.2.1.25.2.1.2"} * hrStorageAllocationUnits{hrStorageType="1.3.6.1.2.1.25.2.1.2"})
        ) > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Device {{ $labels.device }} ({{ $labels.gw }}) memory usage is {{ $value }}%"
          
      - alert: InterfaceHighTraffic
        expr: (rate(ifHCInOctets[5m]) * 8) > 50000000 or (rate(ifHCOutOctets[5m]) * 8) > 500000000
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High interface traffic detected"
          description: "Interface {{ $labels.ifName }} on {{ $labels.device }} has high traffic: In={{ $value }}bps"
          
      - alert: InterfaceDown
        expr: max by (instance, device, gw, ifName, ifIndex) (ifOperStatus{ifOperStatus="up"}) == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Interface is down"
          description: "Interface {{ $labels.ifName }} on {{ $labels.device }} ({{ $labels.gw }}) is down"
          
      - alert: InterfaceHighErrors
        expr: rate(ifInErrors[5m]) > 1 or rate(ifOutErrors[5m]) > 11
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High interface errors detected"
          description: "Interface {{ $labels.ifName }} on {{ $labels.device }} has high error rate: {{ $value }} errors/sec"

  - name: speedtest_alerts
    rules:
      - alert: SlowDownloadSpeed
        expr: speedtest_download_bits_per_second < 20000000  # 20 Mbps
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow download speed detected"
          description: "WAN {{ $labels.line }} ({{ $labels.gateway }}) download speed is {{ $value | humanize }}bps ({{ $value | humanize1024 }}B/s)"
          
      - alert: SlowUploadSpeed
        expr: speedtest_upload_bits_per_second < 20000000  # 20 Mbps
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow upload speed detected"
          description: "WAN {{ $labels.line }} ({{ $labels.gateway }}) upload speed is {{ $value | humanize }}bps ({{ $value | humanize1024 }}B/s)"
          
      - alert: HighPingLatency
        expr: speedtest_ping_latency_milliseconds > 100  # 100ms
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High ping latency detected"
          description: "WAN {{ $labels.line }} ({{ $labels.gateway }}) ping latency is {{ $value }}ms"
          
      - alert: SpeedtestFailed
        expr: speedtest_download_bps == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Speedtest failed"
          description: "WAN {{ $labels.line }} ({{ $labels.gateway }}) speedtest failed - no data received"

  - name: system_alerts
    rules:
      - alert: PrometheusDown
        expr: up{job="prometheus"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Prometheus is down"
          description: "Prometheus monitoring system is not responding"
          
      - alert: SNMPExporterDown
        expr: up{job="snmp-exporter"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "SNMP Exporter is down"
          description: "SNMP Exporter is not responding - network monitoring may be affected"
          
      - alert: GrafanaDown
        expr: up{job="grafana"} == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Grafana is down"
          description: "Grafana dashboard is not accessible"
