global:
  slack_api_url_file: '/run/secrets/slack_webhook'
route:
  group_by: ['alertname', 'device', 'gw']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 1h

receivers:
  - name: 'default-receiver'
    slack_configs:
      - channel: '#hien-test-channel-bot'
        title: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        text: |-
          {{ range .Alerts -}}
          *Status*: {{ .Status | toUpper }}
          *Alert*: {{ .Annotations.summary }}
          *Description*: {{ .Annotations.description }}
          *Device*: {{ .Labels.device }}
          *Gateway*: {{ .Labels.gw }}
          {{ if eq $.Status "resolved" }}*Resolved at*: <!date^{{ .EndsAt.Unix }}^{date_num} {time}|{{ .EndsAt }}>{{ else }}*Starts at*: <!date^{{ .StartsAt.Unix }}^{date_num} {time}|{{ .StartsAt }}>{{ end }}
          ---
          {{- end }}
        send_resolved: true

  - name: 'critical-alerts'
    slack_configs:
      - channel: '#hien-test-channel-bot'
        title: '{{ if eq .Status "resolved" }}RESOLVED ✅{{ else }}CRITICAL 🚨{{ end }}: {{ .GroupLabels.alertname }} - {{ .GroupLabels.device }}'
        text: |-
          {{ range .Alerts -}}
          *Status*: {{ if eq $.Status "resolved" }}RESOLVED{{ else }}FIRING{{ end }}
          *Alert*: {{ .Annotations.summary }}
          *Description*: {{ .Annotations.description }}
          *Device*: {{ .Labels.device }}
          *Gateway*: {{ .Labels.gw }}
          *Severity*: {{ .Labels.severity }}
          {{ if eq $.Status "resolved" }}*Resolved at*: <!date^{{ .EndsAt.Unix }}^{date_num} {time}|{{ .EndsAt }}>{{ else }}*Starts at*: <!date^{{ .StartsAt.Unix }}^{date_num} {time}|{{ .StartsAt }}>{{ end }}
          ---
          {{- end }}
        color: '{{ if eq .Status "resolved" }}#36a64f{{ else }}#ff0000{{ end }}'
        send_resolved: true

  - name: 'warning-alerts'
    slack_configs:
      - channel: '#hien-test-channel-bot'
        title: '{{ if eq .Status "resolved" }}RESOLVED ✅{{ else }}WARNING ⚠️{{ end }}: {{ .GroupLabels.alertname }} - {{ .GroupLabels.device }}'
        text: |-
          {{ range .Alerts -}}
          *Status*: {{ if eq $.Status "resolved" }}RESOLVED{{ else }}FIRING{{ end }}
          *Alert*: {{ .Annotations.summary }}
          *Description*: {{ .Annotations.description }}
          *Device*: {{ .Labels.device }}
          *Gateway*: {{ .Labels.gw }}
          *Severity*: {{ .Labels.severity }}
          {{ if eq $.Status "resolved" }}*Resolved at*: <!date^{{ .EndsAt.Unix }}^{date_num} {time}|{{ .EndsAt }}>{{ else }}*Starts at*: <!date^{{ .StartsAt.Unix }}^{date_num} {time}|{{ .StartsAt }}>{{ end }}
          ---
          {{- end }}
        color: '{{ if eq .Status "resolved" }}#36a64f{{ else }}#ffa500{{ end }}'
        send_resolved: true


