global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmailspam123@gmail.com'
  smtp_auth_username: 'alertmailspam123@gmail.com'
  smtp_auth_password: 'Htt05082004'

route:
  group_by: ['alertname', 'device', 'gw']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 2h

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'alertmailspam123@gmail.com'
        headers:
          Subject: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        html: |
          <h2>Network Alert</h2>
          {{ range .Alerts }}
          <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Device:</strong> {{ .Labels.device }}</p>
          <p><strong>Gateway:</strong> {{ .Labels.gw }}</p>
          <p><strong>Time:</strong> {{ .StartsAt }}</p>
          <hr>
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'alertmailspam123@gmail.com'
        headers:
          Subject: '[CRITICAL] {{ .GroupLabels.alertname }} - {{ .GroupLabels.device }}'
        html: |
          <h2 style="color: red;">🚨 CRITICAL ALERT 🚨</h2>
          {{ range .Alerts }}
          <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Device:</strong> {{ .Labels.device }}</p>
          <p><strong>Gateway:</strong> {{ .Labels.gw }}</p>
          <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
          <p><strong>Time:</strong> {{ .StartsAt }}</p>
          <hr>
          {{ end }}
          <p><strong>Please investigate immediately!</strong></p>

  - name: 'warning-alerts'
    email_configs:
      - to: 'alertmailspam123@gmail.com'
        headers:
          Subject: '[WARNING] {{ .GroupLabels.alertname }} - {{ .GroupLabels.device }}'
        html: |
          <h2 style="color: orange;">⚠️ WARNING ALERT ⚠️</h2>
          {{ range .Alerts }}
          <p><strong>Alert:</strong> {{ .Annotations.summary }}</p>
          <p><strong>Description:</strong> {{ .Annotations.description }}</p>
          <p><strong>Device:</strong> {{ .Labels.device }}</p>
          <p><strong>Gateway:</strong> {{ .Labels.gw }}</p>
          <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
          <p><strong>Time:</strong> {{ .StartsAt }}</p>
          <hr>
          {{ end }}

# Slack configuration (optional)
#  - name: 'slack-alerts'
#    slack_configs:
#      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
#        channel: '#alerts'
#        title: 'Network Alert'
#        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
