global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@yourcompany.com'
  smtp_auth_username: 'alerts@yourcompany.com'
  smtp_auth_password: 'your_password'

route:
  group_by: ['alertname', 'device', 'gw']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 2h

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@yourcompany.com'
        subject: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Device: {{ .Labels.device }}
          Gateway: {{ .Labels.gw }}
          Time: {{ .StartsAt }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@yourcompany.com,oncall@yourcompany.com'
        subject: '[CRITICAL] {{ .GroupLabels.alertname }} - {{ .GroupLabels.device }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Device: {{ .Labels.device }}
          Gateway: {{ .Labels.gw }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt }}
          {{ end }}
          
          Please investigate immediately!

  - name: 'warning-alerts'
    email_configs:
      - to: 'admin@yourcompany.com'
        subject: '[WARNING] {{ .GroupLabels.alertname }} - {{ .GroupLabels.device }}'
        body: |
          ⚠️ WARNING ALERT ⚠️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Device: {{ .Labels.device }}
          Gateway: {{ .Labels.gw }}
          Severity: {{ .Labels.severity }}
          Time: {{ .StartsAt }}
          {{ end }}

# Slack configuration (optional)
#  - name: 'slack-alerts'
#    slack_configs:
#      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
#        channel: '#alerts'
#        title: 'Network Alert'
#        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
