# Loki single-process config (filesystem storage + tsdb index)
# Docs: https://grafana.com/docs/loki/latest/configure/

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9096
  log_level: info

auth_enabled: false  # Set true for multi-tenant with X-Scope-OrgID

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 30m
  chunk_retain_period: 1m

# Schema config with TSDB index (required for v3.5+)
schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

# Storage config for TSDB + filesystem
storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-shipper-cache
  filesystem:
    directory: /loki/chunks

querier:
  max_concurrent: 16
  query_ingesters_within: 2h

query_range:
  parallelise_shardable_queries: true
  max_retries: 5

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  ring:
    kvstore:
      store: inmemory
  enable_api: true

# Limits config with structured metadata enabled (default for TSDB)
limits_config:
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  max_concurrent_tail_requests: 20
  max_cache_freshness_per_query: 10m
  unordered_writes: true
  allow_structured_metadata: true  # Enabled by default with TSDB
  max_query_lookback: 168h  # 7 days

analytics:
  reporting_enabled: false

