global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.10.18:9090']

  - job_name: 'snmp-exporter'
    static_configs:
      - targets: ['192.168.10.18:9116']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.10.18:9100']

  # Network interfaces monitoring (WAN1-WAN4)
  - job_name: 'er5120-interfaces'
    metrics_path: /snmp
    scrape_timeout: 30s
    scrape_interval: 30s
    params:
      module: [if_mib]
      auth: [public_v2c]
    static_configs:
      - targets: ['192.168.10.4']
        labels:
          device: 'ER5120'
          site: 'HQ'
          job_type: 'interfaces'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.10.18:9116

  # Speedtest monitoring - All WAN lines
  - job_name: 'speedtest'
    scrape_interval: 5m  # Default interval for most WANs
    scrape_timeout: 2m
    static_configs:
      # WAN1 - 1h interval (will use 5m due to job-level setting)
      - targets: ['192.168.10.18:9798']
        labels:
          gateway: 'GW1'
          line: 'WAN1'
      
      # WAN2 - 1h interval (will use 5m due to job-level setting)
      - targets: ['192.168.10.18:9799']
        labels:
          gateway: 'GW2'
          gateway1: 'GW5'
          line: 'WAN2'
      
      # WAN3 - 1h interval (will use 5m due to job-level setting)
      - targets: ['192.168.10.18:9800']
        labels:
          gateway: 'GW2'
          gateway1: 'GW5'
          line: 'WAN3'
      
      # WAN4 - 5m interval
      - targets: ['192.168.10.18:9801']
        labels:
          gateway: 'GW4'
          line: 'WAN4'
      
      # WAN5 - 5m interval
      - targets: ['192.168.10.18:9802']
        labels:
          gateway: 'GW4'
          line: 'WAN5'
      
      # WAN6 - 5m interval
      - targets: ['192.168.10.18:9803']
        labels:
          gateway: 'GW4'
          gateway1: 'GW5'
          line: 'WAN6'
      
      # WAN7 - 5m interval
      - targets: ['192.168.10.18:9804']
        labels:
          gateway: 'GW4'
          gateway1: 'GW5'
          line: 'WAN7'
      
      # WAN8 - 1h interval (will use 5m due to job-level setting)
      - targets: ['192.168.10.18:9805']
        labels:
          gateway: 'GW5'
          line: 'WAN8'

