global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 192.168.10.18:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.10.18:9090']

  - job_name: 'snmp-exporter'
    static_configs:
      - targets: ['192.168.10.18:9116']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.10.18:9100']

  - job_name: 'mysqld_exporter'
    static_configs:
      - targets: ['192.168.10.18:9104']

  - job_name: 'grafana'
    static_configs:
      - targets: ['192.168.10.18:3001']

  # Network interfaces monitoring (WAN1-WAN4)
  - job_name: 'gateway-monitor'
    metrics_path: /snmp
    scrape_timeout: 9s
    scrape_interval: 15s
    params:
      module: [if_mib]
      auth: [public_v2c]
    static_configs:
      - targets: ['192.168.10.1']
        labels:
          device: 'ER605'
          gw: 'GW1'
      - targets: ['192.168.10.2']
        labels:
          device: 'LRT224'
          gw: 'GW2'
      - targets: ['192.168.10.4']
        labels:
          device: 'ER5120'
          gw: 'GW4'
      - targets: ['192.168.10.5']
        labels:
          device: 'ER7206'
          gw: 'GW5'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.10.18:9116

  # Speedtest monitoring - split per WAN and staggered intervals
  - job_name: 'speedtest-wan1'
    scrape_interval: 30m
    scrape_timeout: 8m
    static_configs:
      - targets: ['192.168.10.18:9798']
        labels:
          gateway: 'GW1'
          line: 'WAN1'

  - job_name: 'speedtest-wan2'
    scrape_interval: 31m
    scrape_timeout: 8m
    static_configs:
      - targets: ['192.168.10.18:9799']
        labels:
          gateway: 'GW2'
          gateway1: 'GW5'
          line: 'WAN2'

  - job_name: 'speedtest-wan3'
    scrape_interval: 32m
    scrape_timeout: 8m
    static_configs:
      - targets: ['192.168.10.18:9800']
        labels:
          gateway: 'GW2'
          gateway1: 'GW5'
          line: 'WAN3'

  - job_name: 'speedtest-wan4'
    scrape_interval: 33m
    scrape_timeout: 8m
    static_configs:
      - targets: ['192.168.10.18:9801']
        labels:
          gateway: 'GW4'
          line: 'WAN4'

  - job_name: 'speedtest-wan5'
    scrape_interval: 34m
    scrape_timeout: 8m
    static_configs:
      - targets: ['192.168.10.18:9802']
        labels:
          gateway: 'GW4'
          line: 'WAN5'

  - job_name: 'speedtest-wan6'
    scrape_interval: 35m
    scrape_timeout: 8m
    static_configs:
      - targets: ['192.168.10.18:9803']
        labels:
          gateway: 'GW4'
          gateway1: 'GW5'
          line: 'WAN6'

  - job_name: 'speedtest-wan7'
    scrape_interval: 36m
    scrape_timeout: 8m
    static_configs:
      - targets: ['192.168.10.18:9804']
        labels:
          gateway: 'GW4'
          gateway1: 'GW5'
          line: 'WAN7'

  - job_name: 'speedtest-wan8'
    scrape_interval: 37m
    scrape_timeout: 8m
    static_configs:
      - targets: ['192.168.10.18:9805']
        labels:
          gateway: 'GW5'
          line: 'WAN8'

  # Speedtest Japan monitoring - staggered intervals to avoid conflicts


  # Omada Controller Exporter
  - job_name: 'omada-exporter'
    scrape_interval: 15s
    scrape_timeout: 9s
    static_configs:
      - targets: ['192.168.10.18:9202']

  # iPerf3 Exporter v2 - WAN1 (Enhanced by ThanhDeptr)
  # Staggered intervals to avoid concurrent iperf3 tests to same server
  - job_name: 'iperf3-exporter-v2-wan1'
    scrape_interval: 10m
    scrape_timeout: 450s
    metrics_path: '/probe'
    params:
      target: ['13.231.52.162']
      port: ['5201']
      bidirectional: ['true']
      bind_address: ['192.168.10.160']
      parallel: ['2']
      period: ['8s']
    static_configs:
      - targets: ['192.168.10.18:9579']
        labels: 
          wan: 'WAN1'
          region: 'japan'


  # iPerf3 Exporter v2 - WAN2
  - job_name: 'iperf3-exporter-v2-wan2'
    scrape_interval: 10m30s
    scrape_timeout: 450s
    metrics_path: '/probe'
    params:
      target: ['13.231.52.162']
      port: ['5201']
      bidirectional: ['true']
      bind_address: ['192.168.10.161']
      parallel: ['2']
      period: ['8s']
    static_configs:
      - targets: ['192.168.10.18:9579']
        labels:
          wan: 'WAN2'
          region: 'japan'

  # iPerf3 Exporter v2 - WAN3
  - job_name: 'iperf3-exporter-v2-wan3'
    scrape_interval: 11m
    scrape_timeout: 450s
    metrics_path: '/probe'
    params:
      target: ['13.231.52.162']
      port: ['5201']
      bidirectional: ['true']
      bind_address: ['192.168.10.162']
      parallel: ['2']
      period: ['8s']
    static_configs:
      - targets: ['192.168.10.18:9579']
        labels:
          wan: 'WAN3'
          region: 'japan'

  # iPerf3 Exporter v2 - WAN4
  - job_name: 'iperf3-exporter-v2-wan4'
    scrape_interval: 11m30s
    scrape_timeout: 450s
    metrics_path: '/probe'
    params:
      target: ['13.231.52.162']
      port: ['5201']
      bidirectional: ['true']
      bind_address: ['192.168.10.163']
      parallel: ['2']
      period: ['8s']
    static_configs:
      - targets: ['192.168.10.18:9579']
        labels:
          wan: 'WAN4'
          region: 'japan'

  # iPerf3 Exporter v2 - WAN5
  - job_name: 'iperf3-exporter-v2-wan5'
    scrape_interval: 10m
    scrape_timeout: 450s
    metrics_path: '/probe'
    params:
      target: ['13.231.52.162']
      port: ['5201']
      bidirectional: ['true']
      bind_address: ['192.168.10.164']
      parallel: ['2']
      period: ['8s']
    static_configs:
      - targets: ['192.168.10.18:9579']
        labels:
          wan: 'WAN5'
          region: 'japan'

  # iPerf3 Exporter v2 - WAN6
  - job_name: 'iperf3-exporter-v2-wan6'
    scrape_interval: 10m30s
    scrape_timeout: 450s
    metrics_path: '/probe'
    params:
      target: ['13.231.52.162']
      port: ['5201']
      bidirectional: ['true']
      bind_address: ['192.168.10.165']
      parallel: ['2']
      period: ['8s']
    static_configs:
      - targets: ['192.168.10.18:9579']
        labels:
          wan: 'WAN6'
          region: 'japan'

  # iPerf3 Exporter v2 - WAN7
  - job_name: 'iperf3-exporter-v2-wan7'
    scrape_interval: 11m
    scrape_timeout: 450s
    metrics_path: '/probe'
    params:
      target: ['13.231.52.162']
      port: ['5201']
      bidirectional: ['true']
      bind_address: ['192.168.10.166']
      parallel: ['2']
      period: ['8s']
    static_configs:
      - targets: ['192.168.10.18:9579']
        labels:
          wan: 'WAN7'
          region: 'japan'

  # iPerf3 Exporter v2 - WAN8
  - job_name: 'iperf3-exporter-v2-wan8'
    scrape_interval: 11m30s
    scrape_timeout: 450s
    metrics_path: '/probe'
    params:
      target: ['13.231.52.162']
      port: ['5201']
      bidirectional: ['true']
      bind_address: ['192.168.10.167']
      parallel: ['2']
      period: ['8s']
    static_configs:
      - targets: ['192.168.10.18:9579']
        labels:
          wan: 'WAN8'
          region: 'japan'



