auths:
  public_v2c:
    version: 2
    security_level: noauthnopriv
    community: public

modules:
  if_mib:
    walk:
      - 1.3.6.1.2.1.2.2.1.2   # ifDescr
      - 1.3.6.1.2.1.2.2.1.5   # ifSpeed  
      - 1.3.6.1.2.1.2.2.1.8   # ifOperStatus
      - 1.3.6.1.2.1.2.2.1.10  # ifInOctets
      - 1.3.6.1.2.1.2.2.1.16  # ifOutOctets
      - 1.3.6.1.2.1.2.2.1.11  # ifInUcastPkts
      - 1.3.6.1.2.1.2.2.1.17  # ifOutUcastPkts
      - 1.3.6.1.2.1.2.2.1.13  # ifInDiscards
      - 1.3.6.1.2.1.2.2.1.19  # ifOutDiscards
      - 1.3.6.1.2.1.2.2.1.14  # ifInErrors
      - 1.3.6.1.2.1.2.2.1.20  # ifOutErrors
    get:
      - 1.3.6.1.2.1.1.1.0     # sysDescr
      - 1.3.6.1.2.1.1.3.0     # sysUpTime
      - 1.3.6.1.2.1.1.5.0     # sysName
    timeout: 15s
    retries: 2
    lookups:
      - source_indexes: [ifIndex]
        lookup: 1.3.6.1.2.1.2.2.1.2  # ifDescr
        drop_source_indexes: false

  # Module test đơn giản
  simple_test:
    get:
      - 1.3.6.1.2.1.1.1.0     # sysDescr
      - 1.3.6.1.2.1.1.3.0     # sysUpTime
    walk:
      - 1.3.6.1.2.1.2.2.1     # Interface table
    timeout: 10s
    retries: 1

  # Module riêng cho system monitoring
  system_mib:
    walk:
      # System information
      - 1.3.6.1.2.1.1.1.0     # sysDescr
      - 1.3.6.1.2.1.1.3.0     # sysUpTime
      - 1.3.6.1.2.1.1.5.0     # sysName
      # Host resources (if supported)
      - 1.3.6.1.2.1.25.2.2    # hrMemorySize
      - 1.3.6.1.2.1.25.2.3.1.3 # hrStorageType
      - 1.3.6.1.2.1.25.2.3.1.4 # hrStorageDescr
      - 1.3.6.1.2.1.25.2.3.1.5 # hrStorageAllocationUnits
      - 1.3.6.1.2.1.25.2.3.1.6 # hrStorageSize
      - 1.3.6.1.2.1.25.2.3.1.7 # hrStorageUsed
      # Processor information
      - 1.3.6.1.2.1.25.3.3.1.2 # hrProcessorLoad
    timeout: 15s
    retries: 2
