# SNMP Exporter Configuration - Compatible with v0.24.1
auths:
  public_v2c:
    version: 2
    community: public

modules:
  if_mib:
    walk:
      - 1.3.6.1.2.1.2.2.1.2   # ifDescr
      - 1.3.6.1.2.1.2.2.1.5   # ifSpeed
      - 1.3.6.1.2.1.2.2.1.8   # ifOperStatus
      - 1.3.6.1.2.1.2.2.1.10  # ifInOctets
      - 1.3.6.1.2.1.2.2.1.16  # ifOutOctets
      - 1.3.6.1.2.1.2.2.1.11  # ifInUcastPkts
      - 1.3.6.1.2.1.2.2.1.17  # ifOutUcastPkts
      - 1.3.6.1.2.1.2.2.1.13  # ifInDiscards
      - 1.3.6.1.2.1.2.2.1.19  # ifOutDiscards
      - 1.3.6.1.2.1.2.2.1.14  # ifInErrors
      - 1.3.6.1.2.1.2.2.1.20  # ifOutErrors
    get:
      - 1.3.6.1.2.1.1.1.0     # sysDescr
      - 1.3.6.1.2.1.1.3.0     # sysUpTime
      - 1.3.6.1.2.1.1.5.0     # sysName
    timeout: 10s
    retries: 3
    max_repetitions: 25