# SNMP Exporter Configuration - v0.24.1 Minimal
auths:
  public_v2c:
    version: 2
    community: public

modules:
  if_mib:
    walk:
      - 1.3.6.1.2.1.2.2.1.8   # ifOperStatus
    get:
      - 1.3.6.1.2.1.1.1.0     # sysDescr
      - 1.3.6.1.2.1.1.3.0     # sysUpTime
      - 1.3.6.1.2.1.1.5.0     # sysName
    timeout: 10s
    retries: 3
    max_repetitions: 25

  system_mib:
    walk:
      - 1.3.6.1.2.1.1.1.0     # sysDescr
      - 1.3.6.1.2.1.1.3.0     # sysUpTime
      - 1.3.6.1.2.1.1.5.0     # sysName
    get:
      - 1.3.6.1.2.1.1.1.0     # sysDescr
      - 1.3.6.1.2.1.1.3.0     # sysUpTime
      - 1.3.6.1.2.1.1.5.0     # sysName
    timeout: 10s
    retries: 3
    max_repetitions: 25