version: "3.8"

services:
  speedtest1:
    image: ghcr.io/miguelndecarvalho/speedtest-exporter
    container_name: speedtest1
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      SPEEDTEST_ARGS: "--source 192.168.10.160 --accept-license --accept-gdpr --progress=no"
      SPEEDTEST_SERVER: 17758
      SPEEDTEST_PORT: 9798
      LISTEN_ADDRESS: 0.0.0.0:9798
      SPEEDTEST_TIMEOUT: 90
      SPEEDTEST_RETRY: 5
      SPEEDTEST_BACKOFF: 30
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service,instance"
    labels:
      - "service=speedtest-exporter"
      - "instance=speedtest1"


  speedtest2:
    image: ghcr.io/miguelndecarvalho/speedtest-exporter
    container_name: speedtest2
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      SPEEDTEST_ARGS: "--source 192.168.10.161 --accept-license --accept-gdpr --progress=no"
      SPEEDTEST_SERVER: 17758
      SPEEDTEST_PORT: 9799
      SPEEDTEST_TIMEOUT: 90
      SPEEDTEST_RETRY: 5
      SPEEDTEST_BACKOFF: 30
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service,instance"
    labels:
      - "service=speedtest-exporter"
      - "instance=speedtest2"

  speedtest3:
    image: ghcr.io/miguelndecarvalho/speedtest-exporter
    container_name: speedtest3
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      SPEEDTEST_ARGS: "--source 192.168.10.162 --accept-license --accept-gdpr --progress=no"
      SPEEDTEST_SERVER: 17758
      SPEEDTEST_PORT: 9800
      SPEEDTEST_TIMEOUT: 90
      SPEEDTEST_RETRY: 5
      SPEEDTEST_BACKOFF: 30

  speedtest4:
    image: ghcr.io/miguelndecarvalho/speedtest-exporter
    container_name: speedtest4
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      SPEEDTEST_ARGS: "--source 192.168.10.163 --accept-license --accept-gdpr --progress=no"
      SPEEDTEST_SERVER: 17758
      SPEEDTEST_PORT: 9801
      SPEEDTEST_TIMEOUT: 90
      SPEEDTEST_RETRY: 5
      SPEEDTEST_BACKOFF: 30

  speedtest5:
    image: ghcr.io/miguelndecarvalho/speedtest-exporter
    container_name: speedtest5
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      SPEEDTEST_ARGS: "--source 192.168.10.164 --accept-license --accept-gdpr --progress=no"
      SPEEDTEST_SERVER: 17758
      SPEEDTEST_PORT: 9802
      SPEEDTEST_TIMEOUT: 90
      SPEEDTEST_RETRY: 5
      SPEEDTEST_BACKOFF: 30

  speedtest6:
    image: ghcr.io/miguelndecarvalho/speedtest-exporter
    container_name: speedtest6
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      SPEEDTEST_ARGS: "--source 192.168.10.165 --accept-license --accept-gdpr --progress=no"
      SPEEDTEST_SERVER: 17758
      SPEEDTEST_PORT: 9803
      SPEEDTEST_TIMEOUT: 90
      SPEEDTEST_RETRY: 5
      SPEEDTEST_BACKOFF: 30

  speedtest7:
    image: ghcr.io/miguelndecarvalho/speedtest-exporter
    container_name: speedtest7
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      SPEEDTEST_ARGS: "--source 192.168.10.166 --accept-license --accept-gdpr --progress=no"
      SPEEDTEST_SERVER: 17758
      SPEEDTEST_PORT: 9804
      SPEEDTEST_TIMEOUT: 90
      SPEEDTEST_RETRY: 5
      SPEEDTEST_BACKOFF: 30

  speedtest8:
    image: ghcr.io/miguelndecarvalho/speedtest-exporter
    container_name: speedtest8
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      SPEEDTEST_ARGS: "--source 192.168.10.167 --accept-license --accept-gdpr --progress=no"
      SPEEDTEST_SERVER: 17758
      SPEEDTEST_PORT: 9805
      SPEEDTEST_TIMEOUT: 90
      SPEEDTEST_RETRY: 5
      SPEEDTEST_BACKOFF: 30

